const fs = require('fs');

// Function to generate a README content
function generateReadme() {
  const currentDate = new Date().toLocaleDateString();
  
  return `
# My Project README

This is a sample README for your project.

## Overview

This README is generated by a Node.js script on ${currentDate}.

## Usage

Replace this content with information about your project.

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
  `;
}

// Specify the file path for the README.md
const readmeFilePath = 'README.md';

// Generate README content
const readmeContent = generateReadme();

// Write the content to the README.md file
fs.writeFileSync(readmeFilePath, readmeContent);

console.log('README.md file generated successfully.');
