name: Fortnite Stats Update

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the Node.js version you need

      - name: Install Dependencies
        run: npm install
      - name: Post Webhook to Discord (Start)
        if: always()
        run: |
          curl -X POST https://discord.com/api/webhooks/1154207523998552094/8pYZwFQeI-ZRJLPy9JXnp3zXxf6QhFTZjwsCwRovhnzUihiGbpSmaH3w787F2V4gRAcQ  \
               -H 'Content-Type: application/json'  \
               -d '{"content":"Fortnite Stats Update Started"}' 
               
      - name: Run Script Stats Update
        run: node index.js # Replace with the actual name of your script

     
               

      - name: Post Webhook to Discord (End)
        if: always()
        run: |
          curl -X POST https://discord.com/api/webhooks/1154207523998552094/8pYZwFQeI-ZRJLPy9JXnp3zXxf6QhFTZjwsCwRovhnzUihiGbpSmaH3w787F2V4gRAcQ  \
               -H 'Content-Type: application/json'  \
               -d '{"content":"Fortnite Stats Update Completed"}' 

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add README.md
          git commit -m "Update README.md [AUTO]"
          git push
