name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Generate README
        run: node index.js
        env:
          API_SECRET: ${{ secrets.API_SECRET }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git status  # Add this line for debugging
          git add .
          git status  # Add this line for debugging
          git commit -m "Update README.md"
          git push

