name: Fortnite Stats Update

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  update-stats:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node your-script.js # Replace with the actual name of your script

      - name: Post Webhook to Discord (Start)
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Fortnite Stats Update Started"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Post Webhook to Discord (End)
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Fortnite Stats Update Completed"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add README.md
          git commit -m "Update README.md [AUTO]"
          git push
